### ISSUE TITLE
Use standard RMQ-Client api to implement JMS or re-implement an JMS client?

### ISSUE THREAD

**Issue by Zhang-Ke** [rocketmq/rocketmq-jms#1]
What we will discuss is an important thing about the directivity of JMS specification implementation. As everyone knows,  RMQ-Client provides simple api such as DefaultMQProducer/DefaultMQPushConsumer to interactive with RMQ broker. Therefore we have two strategies to implement JMS:

1.  Delegate to DefaultMQProducer/DefaultMQPushConsumer to implement JMS features as many as possible,along with lots of UnsupportedOperationException. It's an easy and fast way to illustrate that RMQ has supported JMS2.0, but so many features can't be supported that I really doubt if we make an eligible open source and if we won't prevent JMS user from adopting RMQ. 

2.  Re-implement a JMS client consisted of RMQ-Client internal codes and some customized codes. It's a bit complicate and need more time to develop, but can support almost all "must" JMS features well and easily to evolution and extend.

    I prefer to the second strategy, but another master @dongeforever prefer to the first one. So I create a discuss issue here to sponsor an review. How do you think about it?

**Comment by lizhanhui** [comment]
My points are:
1. JMS client should be full fledged, aka, complete spec supporting.
2. Reuse existing code base as much as possible. We definitely should NOT be constrained by DefaultMQXXX clients.

**Comment by dongeforever** [comment]
I would not be against  re-implementing a JMS client. But we should keep the consistency of the  RocketMQ Client internal codes, especially the remoting layer and protocol layer. That is we can use  internal code of RocketMQ client, but we do not change it. Otherwise, we will need to maintain two kind of codes.
This project now is separated from the main repository of RocketMQ, it will not be convenient to re-implementing a JMS client as we may not have access to some internal codes.
So in my opinion, it is better to do so in two steps:
1. use RocketMQ client to implement the **basic and most useful features** of JMS 2.0
2. merge this repository to the main of RocketMQ, then we can have another discussion about re-implementation.

@vongosling @zhouxinyu @Zhang-Ke

**Comment by Zhang-Ke** [comment]
Cool, @dongeforever give us another idea. Implement the features in common use to satisfy mostly JMS user. But I must figure out that this implement not only missing some important feature but also against some JMS specification constrains. Task javax.jms.Connection as an example, when calling connection.stop(), JMS specification restrict that all consume should be stopped. But using RMQ-Client it's impossible to conform to this constrain. Another example is that javax.jms.Session is always in a single thread that producer may block consume, it also couldn't be implement by RMQ-Client without customizing codes. I think there are many case through total JMS specification. 

On the other side, current RMQ-Client has much background functionality/thread which is useless to JMS. If user asks us what's that, how we should answer. 

So if our target is to according with JMS specification, at least not violate it, we have to re-write client codes. Of course the remoting layer and protocol layer shouldn't been changed as JMS is not a transport protocol. And we also can copy some logic from current RMQ-Client, but maintain two code base is necessary.  It's just like if we want to provide an C#/Python client, we have to maintain many code base too. There are so many difference between JMS and RMQ-Client, treat JMS Client is another language client is also comprehensible.

**Comment by lizhanhui** [comment]
> "But we should keep the consistency of the RocketMQ Client internal codes, especially the remoting layer and protocol layer. That is we can use internal code of RocketMQ client, but we do not change it. " 

I totally agree on this point, as is following [open/close principle](https://en.wikipedia.org/wiki/Open/closed_principle).

> "This project now is separated from the main repository of RocketMQ, it will not be convenient to re-implementing a JMS client as we may not have access to some internal codes.". 

As a matter of fact, we do have access to internal RocketMQ codes; If there were a need to add an extra feature into broker to support JMS protocol for example, just create a PR and raise an discussion thread. 

> So in my opinion, it is better to do so in two steps:
> 1.  use RocketMQ client to implement the basic and most useful features of JMS 2.0
> 2. merge this repository to the main of RocketMQ, then we can have another discussion about re-implementation."

IMHO, these are specific developing strategies. As long as we can ultimately develop a quality, full-fledged and latest JMS protocol supporting client, we can discuss and choose the preferable approach, be it releasing a few versions supporting essential JMS features earlier or releasing a milestone version supporting protocol fully.

**Comment by lizhanhui** [comment]
> So if our target is to according with JMS specification, at least not violate it, we have to re-write client codes. Of course the remoting layer and protocol layer shouldn't been changed as JMS is not a transport protocol. And we also can copy some logic from current RMQ-Client, but maintain two code base is necessary. It's just like if we want to provide an C#/Python client, we have to maintain many code base too. There are so many difference between JMS and RMQ-Client, treat JMS Client is another language client is also comprehensible.


It's probably okay to add supportive facilities to RocketMQ codebase as long as it does not break current clients.  Actually, to support multiple programming languages, similar  efforts have been made.

**Comment by Zhang-Ke** [comment]
Thanks @lizhanhui to give us positive suggestion. I am just afraid it's nearly impossible to support JMS by enhancing/patching RMQ-Client as they are different design philosophy. How about bring up this question to dev@incubator.rocketmq.apache.org to get more guys opinion?

**Comment by lizhanhui** [comment]
It's totally fine to bring up a thread in mailing list to discuss this issue.

**Comment by dongeforever** [comment]
Now that we have reached the agreement that if we want support JMS fully, we have much work to do, maybe rewrite the client. And we are not sure if JMS can be fully implemented even though we do the rewriting, as JMS and RocketMQ are in different domains with many different concepts.
Let's get into the next discussion:
Releasing a few versions supporting essential JMS features earlier or releasing a milestone version supporting protocol fully?
Maybe we can discuss it in the mailing list.

**Comment by Zhang-Ke** [comment]
Let's push this sub-project forward. How about adopting an eclectic solution:
1. Doesn't change any RMQ-Client code in RocketMQ-JMS project,which means just use RMQ-Client to archive our target at present. 
2. If really need some extra functionality, creating issue onto RMQ Jira. 
3. Refactor current implement of simply delegating to DefaultPushConsumer/DefaultMQProducer. They are so high that make it's difficult to control and conform to JMS spec,especially Connection/Session layer and thread model.

**Comment by iloveyou416068** [comment]
update to current

**Comment by WillemJiang** [comment]
I just have a quick look at the code, the RocketMQ-JMS is not use the latest RocketMQ code. 
If we want to move forward, we need to update the dependency first, then we can change the code of RocketMQ-JMS if we need to.

**Comment by Zhang-Ke** [comment]
Thanks @WillemJiang to give us this suggestion. Sorry for my late reply. 
The RocketMQ-JMS depends on RMQ-Client in runtime scope and RMQ-Broker/RMQ-Namesrv in integration test scope. To keep this project passing through all tests smoothly and not affected by RMQ 4.x bugs during developing stage, maybe depending on a stable RMQ version(3.5.8) is more appropriate than depending on unstable incubating RMQ 4.X. Before releasing the first version of RocketMQ-JMS, of course updating this dependence to a stable RMQ 4.X version is required.  I have created a new issue   #5 for review in the future.
