### ISSUE TITLE
Convert JmsBaseMessage to RocketMQ Message

### ISSUE THREAD

**Issue by dongeforever** [rocketmq/rocketmq-jms#2]
Add a method to MessageConverter:
convert2RMQMessage(JmsBaseMessage jmsMessage)
replace the code block in producer.send() 

Be careful:
 for (String name : properties.stringPropertyNames()) {
                //add filter sys properties?
                rocketmqMsg.putUserProperty(name, properties.getProperty(name));
}
putUserProperty can only put user-defined properties.
So the property name should be checked and use other method like setKeys to set system properties.

**Comment by a2888409** [comment]
i will add this method as soon as possible: convert2RMQMessage(JmsBaseMessage jmsMessage)

**Comment by Zhang-Ke** [comment]
Has been merged into master.
