### ISSUE TITLE
Add more integration test of this milestone

### ISSUE THREAD

**Issue by Zhang-Ke** [rocketmq/rocketmq-jms#30]

**Comment by vongosling** [comment]
cool

**Comment by Zhang-Ke** [comment]
Done. 
The testings of synchronous and asynchronous consume are passed through.
The testings of Unshared-undurable,Unshared-durable,Shared-undurable,Shared-durable consume are passed through.
The testings of integrating spring simple JmsListener are passed through.

A number of functionalities testing are covered by unit test, such as header,built-in properties,messages implements,convert messages between RMQ and JMS, and so on.
